// Agent OS Runtime Protocol
//
// Defines the gRPC interface between Control Plane and Data Plane.
// This is the ONLY communication boundary between the two layers.
//
// Three services:
//   AgentExecutor  - bidirectional streaming for agent execution + HITL
//   ResourceSync   - unary RPCs for syncing rich AgentSpecs and runtime directives
//   SessionQuery   - unary RPCs for checkpoint-backed session reads

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentExecutor_Run_FullMethodName = "/deepagents.runtime.v1.AgentExecutor/Run"
)

// AgentExecutorClient is the client API for AgentExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentExecutorClient interface {
	// Run an agent with bidirectional streaming.
	//
	// Protocol:
	//  1. Client sends RunRequest as the first ClientMessage
	//  2. Server streams AgentEvents (text, tool calls, etc.)
	//  3. If HITL is triggered, server sends HITLRequest and pauses
	//  4. Client sends HITLDecision, server resumes
	//  5. Client may send CancelRequest at any time
	//  6. Stream ends with RunEnded, RunCanceled, or ErrorOccurred
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, AgentEvent], error)
}

type agentExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentExecutorClient(cc grpc.ClientConnInterface) AgentExecutorClient {
	return &agentExecutorClient{cc}
}

func (c *agentExecutorClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentExecutor_ServiceDesc.Streams[0], AgentExecutor_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, AgentEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentExecutor_RunClient = grpc.BidiStreamingClient[ClientMessage, AgentEvent]

// AgentExecutorServer is the server API for AgentExecutor service.
// All implementations must embed UnimplementedAgentExecutorServer
// for forward compatibility.
type AgentExecutorServer interface {
	// Run an agent with bidirectional streaming.
	//
	// Protocol:
	//  1. Client sends RunRequest as the first ClientMessage
	//  2. Server streams AgentEvents (text, tool calls, etc.)
	//  3. If HITL is triggered, server sends HITLRequest and pauses
	//  4. Client sends HITLDecision, server resumes
	//  5. Client may send CancelRequest at any time
	//  6. Stream ends with RunEnded, RunCanceled, or ErrorOccurred
	Run(grpc.BidiStreamingServer[ClientMessage, AgentEvent]) error
	mustEmbedUnimplementedAgentExecutorServer()
}

// UnimplementedAgentExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentExecutorServer struct{}

func (UnimplementedAgentExecutorServer) Run(grpc.BidiStreamingServer[ClientMessage, AgentEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentExecutorServer) mustEmbedUnimplementedAgentExecutorServer() {}
func (UnimplementedAgentExecutorServer) testEmbeddedByValue()                       {}

// UnsafeAgentExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentExecutorServer will
// result in compilation errors.
type UnsafeAgentExecutorServer interface {
	mustEmbedUnimplementedAgentExecutorServer()
}

func RegisterAgentExecutorServer(s grpc.ServiceRegistrar, srv AgentExecutorServer) {
	// If the following call panics, it indicates UnimplementedAgentExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentExecutor_ServiceDesc, srv)
}

func _AgentExecutor_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentExecutorServer).Run(&grpc.GenericServerStream[ClientMessage, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentExecutor_RunServer = grpc.BidiStreamingServer[ClientMessage, AgentEvent]

// AgentExecutor_ServiceDesc is the grpc.ServiceDesc for AgentExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepagents.runtime.v1.AgentExecutor",
	HandlerType: (*AgentExecutorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _AgentExecutor_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "runtime.proto",
}

const (
	ResourceSync_SyncSkill_FullMethodName            = "/deepagents.runtime.v1.ResourceSync/SyncSkill"
	ResourceSync_SyncMcp_FullMethodName              = "/deepagents.runtime.v1.ResourceSync/SyncMcp"
	ResourceSync_SyncAgentSpec_FullMethodName        = "/deepagents.runtime.v1.ResourceSync/SyncAgentSpec"
	ResourceSync_Assemble_FullMethodName             = "/deepagents.runtime.v1.ResourceSync/Assemble"
	ResourceSync_UploadWorkspaceFiles_FullMethodName = "/deepagents.runtime.v1.ResourceSync/UploadWorkspaceFiles"
	ResourceSync_RemoveResource_FullMethodName       = "/deepagents.runtime.v1.ResourceSync/RemoveResource"
	ResourceSync_Health_FullMethodName               = "/deepagents.runtime.v1.ResourceSync/Health"
)

// ResourceSyncClient is the client API for ResourceSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceSyncClient interface {
	// Compatibility RPC for older callers that sync skills separately.
	SyncSkill(ctx context.Context, in *SyncSkillRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Compatibility RPC for older callers that sync MCP configs separately.
	SyncMcp(ctx context.Context, in *SyncMcpRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Push a rich agent spec to the data plane.
	SyncAgentSpec(ctx context.Context, in *SyncAgentSpecRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Trigger agent assembly on the data plane.
	// Prerequisite: the target AgentSpec must already be synced.
	Assemble(ctx context.Context, in *AssembleRequest, opts ...grpc.CallOption) (*AssembleResponse, error)
	// Upload one or more files into an agent/thread workspace.
	UploadWorkspaceFiles(ctx context.Context, in *UploadWorkspaceFilesRequest, opts ...grpc.CallOption) (*UploadWorkspaceFilesResponse, error)
	// Remove a synced runtime resource or cached spec from the data plane.
	RemoveResource(ctx context.Context, in *RemoveResourceRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Health check / readiness probe.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type resourceSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceSyncClient(cc grpc.ClientConnInterface) ResourceSyncClient {
	return &resourceSyncClient{cc}
}

func (c *resourceSyncClient) SyncSkill(ctx context.Context, in *SyncSkillRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ResourceSync_SyncSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceSyncClient) SyncMcp(ctx context.Context, in *SyncMcpRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ResourceSync_SyncMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceSyncClient) SyncAgentSpec(ctx context.Context, in *SyncAgentSpecRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ResourceSync_SyncAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceSyncClient) Assemble(ctx context.Context, in *AssembleRequest, opts ...grpc.CallOption) (*AssembleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssembleResponse)
	err := c.cc.Invoke(ctx, ResourceSync_Assemble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceSyncClient) UploadWorkspaceFiles(ctx context.Context, in *UploadWorkspaceFilesRequest, opts ...grpc.CallOption) (*UploadWorkspaceFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadWorkspaceFilesResponse)
	err := c.cc.Invoke(ctx, ResourceSync_UploadWorkspaceFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceSyncClient) RemoveResource(ctx context.Context, in *RemoveResourceRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ResourceSync_RemoveResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceSyncClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ResourceSync_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceSyncServer is the server API for ResourceSync service.
// All implementations must embed UnimplementedResourceSyncServer
// for forward compatibility.
type ResourceSyncServer interface {
	// Compatibility RPC for older callers that sync skills separately.
	SyncSkill(context.Context, *SyncSkillRequest) (*SyncResponse, error)
	// Compatibility RPC for older callers that sync MCP configs separately.
	SyncMcp(context.Context, *SyncMcpRequest) (*SyncResponse, error)
	// Push a rich agent spec to the data plane.
	SyncAgentSpec(context.Context, *SyncAgentSpecRequest) (*SyncResponse, error)
	// Trigger agent assembly on the data plane.
	// Prerequisite: the target AgentSpec must already be synced.
	Assemble(context.Context, *AssembleRequest) (*AssembleResponse, error)
	// Upload one or more files into an agent/thread workspace.
	UploadWorkspaceFiles(context.Context, *UploadWorkspaceFilesRequest) (*UploadWorkspaceFilesResponse, error)
	// Remove a synced runtime resource or cached spec from the data plane.
	RemoveResource(context.Context, *RemoveResourceRequest) (*SyncResponse, error)
	// Health check / readiness probe.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedResourceSyncServer()
}

// UnimplementedResourceSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceSyncServer struct{}

func (UnimplementedResourceSyncServer) SyncSkill(context.Context, *SyncSkillRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSkill not implemented")
}
func (UnimplementedResourceSyncServer) SyncMcp(context.Context, *SyncMcpRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMcp not implemented")
}
func (UnimplementedResourceSyncServer) SyncAgentSpec(context.Context, *SyncAgentSpecRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAgentSpec not implemented")
}
func (UnimplementedResourceSyncServer) Assemble(context.Context, *AssembleRequest) (*AssembleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Assemble not implemented")
}
func (UnimplementedResourceSyncServer) UploadWorkspaceFiles(context.Context, *UploadWorkspaceFilesRequest) (*UploadWorkspaceFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadWorkspaceFiles not implemented")
}
func (UnimplementedResourceSyncServer) RemoveResource(context.Context, *RemoveResourceRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveResource not implemented")
}
func (UnimplementedResourceSyncServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedResourceSyncServer) mustEmbedUnimplementedResourceSyncServer() {}
func (UnimplementedResourceSyncServer) testEmbeddedByValue()                      {}

// UnsafeResourceSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceSyncServer will
// result in compilation errors.
type UnsafeResourceSyncServer interface {
	mustEmbedUnimplementedResourceSyncServer()
}

func RegisterResourceSyncServer(s grpc.ServiceRegistrar, srv ResourceSyncServer) {
	// If the following call panics, it indicates UnimplementedResourceSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceSync_ServiceDesc, srv)
}

func _ResourceSync_SyncSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).SyncSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_SyncSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).SyncSkill(ctx, req.(*SyncSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceSync_SyncMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).SyncMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_SyncMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).SyncMcp(ctx, req.(*SyncMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceSync_SyncAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).SyncAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_SyncAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).SyncAgentSpec(ctx, req.(*SyncAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceSync_Assemble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssembleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).Assemble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_Assemble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).Assemble(ctx, req.(*AssembleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceSync_UploadWorkspaceFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadWorkspaceFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).UploadWorkspaceFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_UploadWorkspaceFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).UploadWorkspaceFiles(ctx, req.(*UploadWorkspaceFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceSync_RemoveResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).RemoveResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_RemoveResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).RemoveResource(ctx, req.(*RemoveResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceSync_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceSyncServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceSync_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceSyncServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceSync_ServiceDesc is the grpc.ServiceDesc for ResourceSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepagents.runtime.v1.ResourceSync",
	HandlerType: (*ResourceSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncSkill",
			Handler:    _ResourceSync_SyncSkill_Handler,
		},
		{
			MethodName: "SyncMcp",
			Handler:    _ResourceSync_SyncMcp_Handler,
		},
		{
			MethodName: "SyncAgentSpec",
			Handler:    _ResourceSync_SyncAgentSpec_Handler,
		},
		{
			MethodName: "Assemble",
			Handler:    _ResourceSync_Assemble_Handler,
		},
		{
			MethodName: "UploadWorkspaceFiles",
			Handler:    _ResourceSync_UploadWorkspaceFiles_Handler,
		},
		{
			MethodName: "RemoveResource",
			Handler:    _ResourceSync_RemoveResource_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ResourceSync_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime.proto",
}

const (
	SessionQuery_ListSessions_FullMethodName       = "/deepagents.runtime.v1.SessionQuery/ListSessions"
	SessionQuery_GetSession_FullMethodName         = "/deepagents.runtime.v1.SessionQuery/GetSession"
	SessionQuery_GetSessionMessages_FullMethodName = "/deepagents.runtime.v1.SessionQuery/GetSessionMessages"
	SessionQuery_GetLatestSession_FullMethodName   = "/deepagents.runtime.v1.SessionQuery/GetLatestSession"
	SessionQuery_DeleteSession_FullMethodName      = "/deepagents.runtime.v1.SessionQuery/DeleteSession"
)

// SessionQueryClient is the client API for SessionQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query runtime-local session state derived from checkpoint storage.
type SessionQueryClient interface {
	// List recent sessions ordered by latest checkpoint update time.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Get one session summary by agent_name + thread_id.
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	// Read checkpoint-backed session messages for one agent-scoped thread.
	GetSessionMessages(ctx context.Context, in *GetSessionMessagesRequest, opts ...grpc.CallOption) (*GetSessionMessagesResponse, error)
	// Resolve the latest session, optionally filtered by agent.
	GetLatestSession(ctx context.Context, in *GetLatestSessionRequest, opts ...grpc.CallOption) (*GetLatestSessionResponse, error)
	// Delete one local session from checkpoint storage by agent_name + thread_id.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
}

type sessionQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionQueryClient(cc grpc.ClientConnInterface) SessionQueryClient {
	return &sessionQueryClient{cc}
}

func (c *sessionQueryClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionQuery_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionQueryClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, SessionQuery_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionQueryClient) GetSessionMessages(ctx context.Context, in *GetSessionMessagesRequest, opts ...grpc.CallOption) (*GetSessionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionMessagesResponse)
	err := c.cc.Invoke(ctx, SessionQuery_GetSessionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionQueryClient) GetLatestSession(ctx context.Context, in *GetLatestSessionRequest, opts ...grpc.CallOption) (*GetLatestSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestSessionResponse)
	err := c.cc.Invoke(ctx, SessionQuery_GetLatestSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionQueryClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, SessionQuery_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionQueryServer is the server API for SessionQuery service.
// All implementations must embed UnimplementedSessionQueryServer
// for forward compatibility.
//
// Query runtime-local session state derived from checkpoint storage.
type SessionQueryServer interface {
	// List recent sessions ordered by latest checkpoint update time.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Get one session summary by agent_name + thread_id.
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	// Read checkpoint-backed session messages for one agent-scoped thread.
	GetSessionMessages(context.Context, *GetSessionMessagesRequest) (*GetSessionMessagesResponse, error)
	// Resolve the latest session, optionally filtered by agent.
	GetLatestSession(context.Context, *GetLatestSessionRequest) (*GetLatestSessionResponse, error)
	// Delete one local session from checkpoint storage by agent_name + thread_id.
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	mustEmbedUnimplementedSessionQueryServer()
}

// UnimplementedSessionQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionQueryServer struct{}

func (UnimplementedSessionQueryServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionQueryServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionQueryServer) GetSessionMessages(context.Context, *GetSessionMessagesRequest) (*GetSessionMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionMessages not implemented")
}
func (UnimplementedSessionQueryServer) GetLatestSession(context.Context, *GetLatestSessionRequest) (*GetLatestSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSession not implemented")
}
func (UnimplementedSessionQueryServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionQueryServer) mustEmbedUnimplementedSessionQueryServer() {}
func (UnimplementedSessionQueryServer) testEmbeddedByValue()                      {}

// UnsafeSessionQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionQueryServer will
// result in compilation errors.
type UnsafeSessionQueryServer interface {
	mustEmbedUnimplementedSessionQueryServer()
}

func RegisterSessionQueryServer(s grpc.ServiceRegistrar, srv SessionQueryServer) {
	// If the following call panics, it indicates UnimplementedSessionQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionQuery_ServiceDesc, srv)
}

func _SessionQuery_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQuery_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionQuery_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQuery_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionQuery_GetSessionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServer).GetSessionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQuery_GetSessionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServer).GetSessionMessages(ctx, req.(*GetSessionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionQuery_GetLatestSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServer).GetLatestSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQuery_GetLatestSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServer).GetLatestSession(ctx, req.(*GetLatestSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionQuery_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQuery_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionQuery_ServiceDesc is the grpc.ServiceDesc for SessionQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepagents.runtime.v1.SessionQuery",
	HandlerType: (*SessionQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _SessionQuery_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionQuery_GetSession_Handler,
		},
		{
			MethodName: "GetSessionMessages",
			Handler:    _SessionQuery_GetSessionMessages_Handler,
		},
		{
			MethodName: "GetLatestSession",
			Handler:    _SessionQuery_GetLatestSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionQuery_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime.proto",
}
